echo POSTGRES_USER = $POSTGRES_USER >> .env
echo POSTGRES_PASSWORD = $POSTGRES_PASSWORD >> .env
echo POSTGRES_HOST = $POSTGRES_HOST >> .env
echo POSTGRES_PORT = $POSTGRES_PORT >> .env
echo POSTGRES_DB = $POSTGRES_DB >> .env
echo PGADMIN_DEFAULT_EMAIL = $PGADMIN_DEFAULT_EMAIL >> .env
echo PGADMIN_DEFAULT_PASSWORD = $PGADMIN_DEFAULT_PASSWORD >> .env
