name: Build and Push to GitHub Container Registry

on:
  push:
    branches:
      - main 

env:
  POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
  POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
  POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
  POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
  POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
  PGADMIN_DEFAULT_EMAIL: ${{ secrets.PGADMIN_DEFAULT_EMAIL }}
  PGADMIN_DEFAULT_PASSWORD: ${{ secrets.PGADMIN_DEFAULT_PASSWORD }}

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest 

    permissions:
      contents: read
      packages: write 

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup environment variables
        run: |
          chmod +x setup_env.sh
          ./setup_env.sh

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        run: docker compose build

      - name: Push Docker image
        run: docker compose push

  befor-deploy:
        name: Before deploy
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/main'
        needs: build-and-push
        steps:
          - uses: actions/checkout@v3
          - name: Set env file
            run: |
                chmod +x ./setup_env.sh
                bash ./setup_env.sh
          - name: copy file from ssh key
            uses: appleboy/scp-action@v0.1.4
            with:
              host: ${{secrets.DEPLOY_PUBLIC_IP_ADDRESS}}
              username: ${{secrets.SERVER_USER}}
              key: ${{secrets.PRIVATE_KEY}}
              port: 22
              source: "./.env, ./docker-compose.prod.yml"
              target: "/${{secrets.SERVER_USER}}/projects/djanog_to_deploy_2"